--
-- PostgreSQL database dump
--

\restrict 1bdYbQXAI7hOfpHnkCJMsugxleSTlCAKc9dEQNSeguYIXBKhvd9Lwl969IpBdKy

-- Dumped from database version 17.10 (Ubuntu 17.10-0ubuntu0.25.10.1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_category (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    title_en character varying(255),
    description text NOT NULL,
    description_en text,
    "order" integer NOT NULL,
    icon character varying(100),
    description_el text,
    title_el character varying(255),
    CONSTRAINT core_category_order_check CHECK (("order" >= 0))
);


--
-- Name: core_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_combo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_combo (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    title_en character varying(255),
    short_description character varying(255) NOT NULL,
    short_description_en character varying(255),
    description text NOT NULL,
    description_en text,
    price numeric(10,2) NOT NULL,
    image character varying(100) NOT NULL,
    image_2 character varying(100),
    image_3 character varying(100),
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    category_id bigint NOT NULL,
    short_description_el character varying(255),
    description_el text,
    title_el character varying(255),
    CONSTRAINT core_combo_order_check CHECK (("order" >= 0))
);


--
-- Name: core_combo_dishes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_combo_dishes (
    id bigint NOT NULL,
    combo_id bigint NOT NULL,
    dish_id bigint NOT NULL
);


--
-- Name: core_combo_dishes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_combo_dishes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_combo_dishes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_combo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_combo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_combo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_combocategory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_combocategory (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    title_en character varying(255),
    description text NOT NULL,
    description_en text,
    icon character varying(100),
    "order" integer NOT NULL,
    description_el text,
    title_el character varying(255),
    CONSTRAINT core_combocategory_order_check CHECK (("order" >= 0))
);


--
-- Name: core_combocategory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_combocategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_combocategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_dish; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_dish (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    title_en character varying(255),
    description text NOT NULL,
    description_en text,
    price numeric(10,2) NOT NULL,
    image character varying(100),
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    category_id bigint NOT NULL,
    short_description character varying(255) NOT NULL,
    short_description_en character varying(255),
    image_2 character varying(100),
    image_3 character varying(100),
    weight character varying(50),
    short_description_el character varying(255),
    description_el text,
    title_el character varying(255),
    CONSTRAINT core_dish_order_check CHECK (("order" >= 0))
);


--
-- Name: core_dish_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_dish_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_dish_tags (
    id bigint NOT NULL,
    dish_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: core_dish_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_dish_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_dish_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_tag (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    title_en character varying(255),
    "order" integer NOT NULL,
    color_bg character varying(50) NOT NULL,
    color_text character varying(20) NOT NULL,
    show_on_card boolean NOT NULL,
    color_bg_hex character varying(20) NOT NULL,
    opacity double precision NOT NULL,
    title_el character varying(255),
    CONSTRAINT core_tag_order_check CHECK (("order" >= 0))
);


--
-- Name: core_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.core_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: orders_order; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders_order (
    id bigint NOT NULL,
    customer_name character varying(100) NOT NULL,
    customer_phone character varying(20) NOT NULL,
    address character varying(255),
    comment text,
    total_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_orderitem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders_orderitem (
    id bigint NOT NULL,
    dish_name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    dish_id bigint,
    order_id bigint NOT NULL,
    CONSTRAINT orders_orderitem_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Категория меню	7	add_category
26	Can change Категория меню	7	change_category
27	Can delete Категория меню	7	delete_category
28	Can view Категория меню	7	view_category
29	Can add Блюдо	10	add_dish
30	Can change Блюдо	10	change_dish
31	Can delete Блюдо	10	delete_dish
32	Can view Блюдо	10	view_dish
33	Can add Категория сборки	9	add_combocategory
34	Can change Категория сборки	9	change_combocategory
35	Can delete Категория сборки	9	delete_combocategory
36	Can view Категория сборки	9	view_combocategory
37	Can add Сборка	8	add_combo
38	Can change Сборка	8	change_combo
39	Can delete Сборка	8	delete_combo
40	Can view Сборка	8	view_combo
41	Can add Тег	11	add_tag
42	Can change Тег	11	change_tag
43	Can delete Тег	11	delete_tag
44	Can view Тег	11	view_tag
45	Can add Позиция заказа	13	add_orderitem
46	Can change Позиция заказа	13	change_orderitem
47	Can delete Позиция заказа	13	delete_orderitem
48	Can view Позиция заказа	13	view_orderitem
49	Can add Заказ	12	add_order
50	Can change Заказ	12	change_order
51	Can delete Заказ	12	delete_order
52	Can view Заказ	12	view_order
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$uZMqkUe8OPHUgGVvPwZYbn$x3+JZwCU8o2DelEyIY0CswHyAoi5f+LAns+2e4PKsG4=	2026-07-23 12:49:26.325616+00	t	dastorkon				t	t	2026-06-01 21:41:12.515903+00
2	pbkdf2_sha256$1200000$bODViYhgoXEa79txLOMl4T$f2e6nYwDMHWJukf400YrZOs1s+NYzwZKCPY5MCgYYT4=	2026-07-23 17:32:16.925941+00	t	god			god@gmail.com	t	t	2026-07-03 18:40:48.812628+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_category; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_category (id, title, title_en, description, description_en, "order", icon, description_el, title_el) FROM stdin;
157	Κρύο Μεζέ	Cold Meze	Παραδοσιακά κρύα ορεκτικά του κυπριακού μεζέ, φτιαγμένα στο χέρι στο σπίτι.	Traditional cold appetizers of the Cypriot meze, hand-made at home.	0		Παραδοσιακά κρύα ορεκτικά του κυπριακού μεζέ, φτιαγμένα στο χέρι στο σπίτι.	Κρύο Μεζέ
158	Ζεστό Μεζέ	Hot Meze	Ζεστά ορεκτικά από τη σχάρα και το τηγάνι, με γεύσεις από την κυπριακή γη.	Hot appetizers from the grill and frying pan, with flavours of the Cypriot land.	1		Ζεστά ορεκτικά από τη σχάρα και το τηγάνι, με γεύσεις από την κυπριακή γη.	Ζεστό Μεζέ
159	Από τα Κάρβουνα	From the Charcoal	Ψητά στα κάρβουνα του χαρουπιού — το χαρακτηριστικό άρωμα της ταβέρνας μας.	Grilled over carob charcoal — the signature aroma of our tavern.	2		Ψητά στα κάρβουνα του χαρουπιού — το χαρακτηριστικό άρωμα της ταβέρνας μας.	Από τα Κάρβουνα
160	Από τον Ξυλόφουρνο	From the Wood-Fired Oven	Πιάτα αργά μαγειρεμένα στον παραδοσιακό ξυλόφουρνο.	Dishes slow-cooked in the traditional wood-fired oven.	3		Πιάτα αργά μαγειρεμένα στον παραδοσιακό ξυλόφουρνο.	Από τον Ξυλόφουρνο
161	Σαλάτες	Salads	Φρέσκες σαλάτες με εποχικά λαχανικά από την περιοχή.	Fresh salads with seasonal vegetables from the region.	4		Φρέσκες σαλάτες με εποχικά λαχανικά από την περιοχή.	Σαλάτες
162	Σπιτικά Γλυκά	Home-Made Sweets	Παραδοσιακά κυπριακά γλυκά, φτιαγμένα στο σπίτι.	Traditional Cypriot desserts, made at home.	5		Παραδοσιακά κυπριακά γλυκά, φτιαγμένα στο σπίτι.	Σπιτικά Γλυκά
163	Ποτά & Σπιτικό Κρασί	Drinks & Home-Made Wine	Σπιτικό κρασί, ζιβανία και παραδοσιακά ποτά της ταβέρνας.	Home-made wine, zivania and traditional tavern drinks.	6		Σπιτικό κρασί, ζιβανία και παραδοσιακά ποτά της ταβέρνας.	Ποτά & Σπιτικό Κρασί
164	Βίγκαν Μεζέ	Vegan Meze	Πλήρες βίγκαν μεζέ — χωρίς ζωικά προϊόντα, με την ίδια αγάπη.	A full vegan meze — no animal products, with the same love.	7		Πλήρες βίγκαν μεζέ — χωρίς ζωικά προϊόντα, με την ίδια αγάπη.	Βίγκαν Μεζέ
\.


--
-- Data for Name: core_combo; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_combo (id, title, title_en, short_description, short_description_en, description, description_en, price, image, image_2, image_3, is_active, "order", category_id, short_description_el, description_el, title_el) FROM stdin;
7	Κυπριακό Μεζέ για Δύο	Cypriot Meze for Two	Πλήρες μεζέ για δύο — πάνω από 20 πιάτα.	Full meze for two — over 20 dishes.	Η κλασική κυπριακή εμπειρία μεζέ για δύο: κρύο και ζεστό μεζέ, σχάρα στα κάρβουνα, πιάτα από τον ξυλόφουρνο, σπιτικά γλυκά και κρασί. Πάνω από 20 πιάτα, σερβιρισμένα αργά, όπως επιτάσσει η παράδοση.	The classic Cypriot meze experience for two: cold and hot meze, charcoal grill, wood-fired oven dishes, home-made sweets and wine. Over 20 dishes served slowly, as tradition demands.	48.00				t	0	3	Πλήρες μεζέ για δύο — πάνω από 20 πιάτα.	Η κλασική κυπριακή εμπειρία μεζέ για δύο: κρύο και ζεστό μεζέ, σχάρα στα κάρβουνα, πιάτα από τον ξυλόφουρνο, σπιτικά γλυκά και κρασί. Πάνω από 20 πιάτα, σερβιρισμένα αργά, όπως επιτάσσει η παράδοση.	Κυπριακό Μεζέ για Δύο
8	Οικογενειακό Μεζέ	Family Meze	Άφθονο μεζέ για όλη την οικογένεια.	Abundant meze for the whole family.	Γενναιόδωρο οικογενειακό μεζέ για 4–6 άτομα, με μεγάλη ποικιλία από πιάτα της σχάρας και του ξυλόφουρνου, σαλάτες και γλυκά — όπως μαζεύονται οι κυπριακές οικογένειες στο τραπέζι.	A generous family-style meze for 4–6 people, with a wide selection of charcoal and oven dishes, salads and sweets — the way Cypriot families gather at the table.	89.00				t	1	3	Άφθονο μεζέ για όλη την οικογένεια.	Γενναιόδωρο οικογενειακό μεζέ για 4–6 άτομα, με μεγάλη ποικιλία από πιάτα της σχάρας και του ξυλόφουρνου, σαλάτες και γλυκά — όπως μαζεύονται οι κυπριακές οικογένειες στο τραπέζι.	Οικογενειακό Μεζέ
9	Βίγκαν Μεζέ	Vegan Meze	Πλήρες βίγκαν μεζέ με σπιτικά πιάτα.	Full vegan meze with home-made dishes.	Πλήρες βίγκαν μεζέ με πάνω από 15 φυτικά πιάτα: ντιπ, κεφτεδάκια, γεμιστά, εποχικές σαλάτες και γλυκά — απόδειξη ότι η κυπριακή φιλοξενία είναι για όλους.	A full vegan meze with over 15 plant-based dishes: dips, keftedes, stuffed vegetables, seasonal salads and sweets — proof that Cypriot hospitality is for everyone.	35.00				t	2	3	Πλήρες βίγκαν μεζέ με σπιτικά πιάτα.	Πλήρες βίγκαν μεζέ με πάνω από 15 φυτικά πιάτα: ντιπ, κεφτεδάκια, γεμιστά, εποχικές σαλάτες και γλυκά — απόδειξη ότι η κυπριακή φιλοξενία είναι για όλους.	Βίγκαν Μεζέ
\.


--
-- Data for Name: core_combo_dishes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_combo_dishes (id, combo_id, dish_id) FROM stdin;
\.


--
-- Data for Name: core_combocategory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_combocategory (id, title, title_en, description, description_en, icon, "order", description_el, title_el) FROM stdin;
3	Μεζέ Σετ	Meze Sets	Πλήρη σετ μεζέ για το τραπέζι σας — η ουσία της κυπριακής ταβέρνας.	Full meze sets for your table — the essence of a Cypriot tavern.		0	Πλήρη σετ μεζέ για το τραπέζι σας — η ουσία της κυπριακής ταβέρνας.	Μεζέ Σετ
\.


--
-- Data for Name: core_dish; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_dish (id, title, title_en, description, description_en, price, image, is_active, "order", category_id, short_description, short_description_en, image_2, image_3, weight, short_description_el, description_el, title_el) FROM stdin;
1250	Σπιτικό Ταχίνι	Home-Made Tahini	Κρεμώδες σπιτικό ταχίνι από επιλεγμένο σουσάμι, με φρέσκο λεμόνι και ελαιόλαδο. Συνοδεύεται με ζεστό ψωμί απ' τον ξυλόφουρνο.	Creamy home-made tahini from selected sesame, with fresh lemon and olive oil. Served with warm bread from the wood-fired oven.	6.50		t	0	157	Σπιτικό ταχίνι με λεμόνι, σερβιρισμένο με φρέσκο ψωμί.	Home-made tahini with lemon, served with fresh bread.			200g	Σπιτικό ταχίνι με λεμόνι, σερβιρισμένο με φρέσκο ψωμί.	Κρεμώδες σπιτικό ταχίνι από επιλεγμένο σουσάμι, με φρέσκο λεμόνι και ελαιόλαδο. Συνοδεύεται με ζεστό ψωμί απ' τον ξυλόφουρνο.	Σπιτικό Ταχίνι
1251	Ντολμάδες	Dolmades	Παραδοσιακοί ντολμάδες: αμπελόφυλλα τυλιγμένα στο χέρι, γεμιστά με ρύζι, δυόσμο και κυπριακά βότανα, περιχυμένα με ελαιόλαδο.	Traditional dolmades: hand-rolled vine leaves stuffed with rice, mint and Cypriot herbs, drizzled with olive oil.	7.50		t	1	157	Αμπελόφυλλα γεμιστά με ρύζι, βότανα και ελαιόλαδο.	Vine leaves stuffed with rice, herbs and olive oil.			6 τεμάχια / 6 pieces	Αμπελόφυλλα γεμιστά με ρύζι, βότανα και ελαιόλαδο.	Παραδοσιακοί ντολμάδες: αμπελόφυλλα τυλιγμένα στο χέρι, γεμιστά με ρύζι, δυόσμο και κυπριακά βότανα, περιχυμένα με ελαιόλαδο.	Ντολμάδες
1252	Ταραμοσαλάτα	Taramosalata	Απαλή ταραμοσαλάτα από αυγά ψαριού, ψωμί και ελαιόλαδο, με λεπτή υφή και ισορροπημένη γεύση.	Velvety taramosalata made from fish roe, bread and olive oil, with a delicate texture and balanced taste.	6.50		t	2	157	Κρεμώδης ταραμοσαλάτα με φρέσκο ψωμί.	Creamy taramosalata served with fresh bread.			200g	Κρεμώδης ταραμοσαλάτα με φρέσκο ψωμί.	Απαλή ταραμοσαλάτα από αυγά ψαριού, ψωμί και ελαιόλαδο, με λεπτή υφή και ισορροπημένη γεύση.	Ταραμοσαλάτα
1253	Χαλούμι τηγανητό	Fried Halloumi	Φρέσκο κυπριακό χαλούμι, τηγανισμένο μέχρι να ροδίσει, σερβιρισμένο με φρέσκο λεμόνι και δυόσμο.	Fresh Cypriot halloumi, pan-fried until golden, served with fresh lemon and mint.	8.00		t	0	158	Κυπριακό χαλούμι τηγανητό, σερβιρισμένο με λεμόνι.	Fried Cypriot halloumi, served with lemon.			250g	Κυπριακό χαλούμι τηγανητό, σερβιρισμένο με λεμόνι.	Φρέσκο κυπριακό χαλούμι, τηγανισμένο μέχρι να ροδίσει, σερβιρισμένο με φρέσκο λεμόνι και δυόσμο.	Χαλούμι τηγανητό
1254	Κεφτεδάκια λαχανικών	Vegetable Keftedes	Κεφτεδάκια από φρέσκα λαχανικά και μυρωδικά, τηγανισμένα μέχρι να γίνουν τραγανά έξω και αφράτα μέσα.	Keftedes made from fresh vegetables and herbs, fried until crispy outside and fluffy inside.	7.00		t	1	158	Τραγανά κεφτεδάκια λαχανικών με βότανα.	Crispy vegetable keftedes with herbs.			6 τεμάχια / 6 pieces	Τραγανά κεφτεδάκια λαχανικών με βότανα.	Κεφτεδάκια από φρέσκα λαχανικά και μυρωδικά, τηγανισμένα μέχρι να γίνουν τραγανά έξω και αφράτα μέσα.	Κεφτεδάκια λαχανικών
1255	Τραχανάς	Trahanas	Χειροποίητος τραχανάς μαγειρεμένος αργά, με γλυκιά γεύση ζύμης και τοπικό τυρί.	Hand-made trahanas cooked slowly, with a sweet fermented flavour and local cheese.	8.50		t	2	158	Παραδοσιακός κυπριακός τραχανάς με τυρί.	Traditional Cypriot trahanas with cheese.			300g	Παραδοσιακός κυπριακός τραχανάς με τυρί.	Χειροποίητος τραχανάς μαγειρεμένος αργά, με γλυκιά γεύση ζύμης και τοπικό τυρί.	Τραχανάς
1256	Σουβλάκι	Souvlaki	Κλασικό κυπριακό σουβλάκι σε ξύλινο σουβλάκι, ψημένο στα κάρβουνα του χαρουπιού, με χαρακτηριστικό καπνιστό άρωμα.	Classic Cypriot souvlaki on a wooden skewer, grilled over carob charcoal with its signature smoky aroma.	12.00		t	0	159	Χοιρινό σουβλάκι στα κάρβουνα του χαρουπιού.	Pork souvlaki grilled over carob charcoal.			250g	Χοιρινό σουβλάκι στα κάρβουνα του χαρουπιού.	Κλασικό κυπριακό σουβλάκι σε ξύλινο σουβλάκι, ψημένο στα κάρβουνα του χαρουπιού, με χαρακτηριστικό καπνιστό άρωμα.	Σουβλάκι
1257	Σεφταλιά	Sheftalia	Παραδοσιακή κυπριακή σεφταλιά: κιμάς χοιρινού με μυρωδικά, τυλιγμένος σε δίχτυ, ψημένος στα κάρβουνα.	Traditional Cypriot sheftalia: minced pork with herbs, wrapped in caul fat, grilled over charcoal.	11.00		t	1	159	Χειροποίητη σεφταλιά απ' τη σχάρα.	Hand-made sheftalia from the grill.			250g	Χειροποίητη σεφταλιά απ' τη σχάρα.	Παραδοσιακή κυπριακή σεφταλιά: κιμάς χοιρινού με μυρωδικά, τυλιγμένος σε δίχτυ, ψημένος στα κάρβουνα.	Σεφταλιά
1258	Λούντζα με κρασί	Lountza in Wine Sauce	Καπνιστή χοιρινή λούντζα, μαγειρεμένη σε γλυκιά σάλτσα κόκκινου κρασιού, με άρωμα κανέλας.	Smoked pork lountza, cooked in a sweet red wine sauce with a hint of cinnamon.	13.00		t	2	159	Καπνιστή λούντζα σε σάλτσα κρασιού.	Smoked lountza in a wine sauce.			280g	Καπνιστή λούντζα σε σάλτσα κρασιού.	Καπνιστή χοιρινή λούντζα, μαγειρεμένη σε γλυκιά σάλτσα κόκκινου κρασιού, με άρωμα κανέλας.	Λούντζα με κρασί
1259	Ρέσι	Resi	Το ρέσι είναι ένα παραδοσιακό γαμήλιο πιάτο: χοιρινό και κοτόπουλο με σιτάρι, μαγειρεμένα αργά στον ξυλόφουρνο, όπως στην παράδοση.	Resi is a traditional wedding dish: pork and chicken with wheat, slow-cooked in the wood-fired oven, as tradition demands.	14.50		t	0	160	Παραδοσιακό γαμήλιο πιάτο της Κύπρου.	Traditional Cypriot wedding dish.			350g	Παραδοσιακό γαμήλιο πιάτο της Κύπρου.	Το ρέσι είναι ένα παραδοσιακό γαμήλιο πιάτο: χοιρινό και κοτόπουλο με σιτάρι, μαγειρεμένα αργά στον ξυλόφουρνο, όπως στην παράδοση.	Ρέσι
1260	Κλέφτικο	Kleftiko	Αρνί μαριναρισμένο με δεντρολίβανο και λεμόνι, τυλιγμένο σε περγαμηνή και ψημένο αργά στον ξυλόφουρνο μέχρι να λιώνει.	Lamb marinated with rosemary and lemon, wrapped in parchment and roasted slowly in the wood-fired oven until it melts.	15.50		t	1	160	Αρνί αργομαγειρεμένο στον ξυλόφουρνο.	Lamb slow-cooked in the wood-fired oven.			350g	Αρνί αργομαγειρεμένο στον ξυλόφουρνο.	Αρνί μαριναρισμένο με δεντρολίβανο και λεμόνι, τυλιγμένο σε περγαμηνή και ψημένο αργά στον ξυλόφουρνο μέχρι να λιώνει.	Κλέφτικο
1261	Χωριάτικη σαλάτα	Village Salad	Ντομάτα, αγγούρι, κρεμμύδι, ελιές και φέτα, με ελαιόλαδο και ρίγανη από το βουνό.	Tomato, cucumber, onion, olives and feta, with olive oil and mountain oregano.	8.50		t	0	161	Φρέσκια χωριάτικη με φέτα και ελιές.	Fresh village salad with feta and olives.			350g	Φρέσκια χωριάτικη με φέτα και ελιές.	Ντομάτα, αγγούρι, κρεμμύδι, ελιές και φέτα, με ελαιόλαδο και ρίγανη από το βουνό.	Χωριάτικη σαλάτα
1262	Σαλάτα με χαλούμι	Halloumi Salad	Χαλούμι στη σχάρα πάνω σε φρέσκα εποχικά λαχανικά, με dressing λεμονιού και ελαιόλαδο.	Grilled halloumi over fresh seasonal vegetables, with a lemon and olive oil dressing.	10.00		t	1	161	Χαλούμι στη σχάρα με εποχικά λαχανικά.	Grilled halloumi with seasonal vegetables.			300g	Χαλούμι στη σχάρα με εποχικά λαχανικά.	Χαλούμι στη σχάρα πάνω σε φρέσκα εποχικά λαχανικά, με dressing λεμονιού και ελαιόλαδο.	Σαλάτα με χαλούμι
1263	Γλυκές λουκουμάδες	Sweet Loukoumades	Αφράτοι λουκουμάδες περιχυμένοι με κυπριακό μέλι, πασπαλισμένοι με κανέλα και καρύδια.	Fluffy loukoumades drizzled with Cypriot honey, dusted with cinnamon and walnuts.	6.00		t	0	162	Λουκουμάδες με μέλι και κανέλα.	Loukoumades with honey and cinnamon.			8 τεμάχια / 8 pieces	Λουκουμάδες με μέλι και κανέλα.	Αφράτοι λουκουμάδες περιχυμένοι με κυπριακό μέλι, πασπαλισμένοι με κανέλα και καρύδια.	Γλυκές λουκουμάδες
1264	Μπακλαβάς	Baklava	Λεπτά φύλλα ζύμης με αμύγδαλα, μέλι και άρωμα ανθοκεράσι — φτιαγμένος στο χέρι στο σπίτι.	Thin filo layers with almonds, honey and orange blossom — hand-made at home.	5.50		t	1	162	Σπιτικός μπακλαβάς με αμύγδαλα.	Home-made baklava with almonds.			2 τεμάχια / 2 pieces	Σπιτικός μπακλαβάς με αμύγδαλα.	Λεπτά φύλλα ζύμης με αμύγδαλα, μέλι και άρωμα ανθοκεράσι — φτιαγμένος στο χέρι στο σπίτι.	Μπακλαβάς
1265	Σπιτικό κρασί	Home-Made Wine	Κρασί από τα δικά μας αμπέλια, κόκκινο ή λευκό, σερβιρισμένο παραδοσιακά στο τραπέζι.	Wine from our own vineyards, red or white, served traditionally at the table.	4.00		t	0	163	Κρασί παραγωγής μας, κόκκινο ή λευκό.	Our own wine, red or white.			250ml	Κρασί παραγωγής μας, κόκκινο ή λευκό.	Κρασί από τα δικά μας αμπέλια, κόκκινο ή λευκό, σερβιρισμένο παραδοσιακά στο τραπέζι.	Σπιτικό κρασί
1266	Ζιβανία	Zivania	Παραδοσιακή κυπριακή ζιβανία από απόσταγμα σταφυλιού, σερβιρισμένη παγωμένη.	Traditional Cypriot zivania, a grape-based spirit, served ice-cold.	5.00		t	1	163	Παραδοσιακό κυπριακό απόσταγμα.	Traditional Cypriot spirit.			50ml	Παραδοσιακό κυπριακό απόσταγμα.	Παραδοσιακή κυπριακή ζιβανία από απόσταγμα σταφυλιού, σερβιρισμένη παγωμένη.	Ζιβανία
1267	Βίγκαν κεφτεδάκια	Vegan Keftedes	Βίγκαν κεφτεδάκια από ρεβίθια, κρεμμύδι και φρέσκα βότανα, τηγανισμένα και σερβιρισμένα με ντιπ.	Vegan keftedes from chickpeas, onion and fresh herbs, fried and served with a dip.	7.50		t	0	164	Κεφτεδάκια με ρεβίθια και βότανα.	Chickpea keftedes with herbs.			6 τεμάχια / 6 pieces	Κεφτεδάκια με ρεβίθια και βότανα.	Βίγκαν κεφτεδάκια από ρεβίθια, κρεμμύδι και φρέσκα βότανα, τηγανισμένα και σερβιρισμένα με ντιπ.	Βίγκαν κεφτεδάκια
1268	Γεμιστά λαχανικά	Stuffed Vegetables	Ντομάτες και πιπεριές γεμιστές με ρύζι, δυόσμο και μυρωδικά, ψημένες στο λάδι.	Tomatoes and peppers stuffed with rice, mint and herbs, baked in oil.	9.00		t	1	164	Γεμιστά ντοματίνια και πιπεριές με ρύζι.	Stuffed tomatoes and peppers with rice.			350g	Γεμιστά ντοματίνια και πιπεριές με ρύζι.	Ντομάτες και πιπεριές γεμιστές με ρύζι, δυόσμο και μυρωδικά, ψημένες στο λάδι.	Γεμιστά λαχανικά
\.


--
-- Data for Name: core_dish_tags; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_dish_tags (id, dish_id, tag_id) FROM stdin;
68	1250	33
69	1250	34
70	1251	32
71	1251	33
72	1251	35
73	1252	34
74	1253	32
75	1253	34
76	1253	35
77	1254	32
78	1254	34
79	1255	34
80	1256	30
81	1257	30
82	1257	31
83	1258	30
84	1259	34
85	1259	30
86	1260	31
87	1261	32
88	1261	35
89	1262	32
90	1262	35
91	1263	32
92	1263	34
93	1264	32
94	1264	34
95	1265	34
96	1266	34
97	1267	33
98	1267	34
99	1268	32
100	1268	33
\.


--
-- Data for Name: core_tag; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.core_tag (id, title, title_en, "order", color_bg, color_text, show_on_card, color_bg_hex, opacity, title_el) FROM stdin;
30	Υπογραφή	\N	0	rgba(184,92,56,1.0)	#FFFFFF	t	#B85C38	1	Υπογραφή
31	Από τα Κάρβουνα	\N	0	rgba(46,63,53,1.0)	#FFFFFF	t	#2E3F35	1	Από τα Κάρβουνα
32	Χορτοφαγικό	\N	0	rgba(107,123,79,1.0)	#FFFFFF	t	#6B7B4F	1	Χορτοφαγικό
33	Βίγκαν	\N	0	rgba(46,82,102,1.0)	#FFFFFF	t	#2E5266	1	Βίγκαν
34	Σπιτικό	\N	0	rgba(169,196,219,1.0)	#000000	t	#A9C4DB	1	Σπιτικό
35	Χωρίς Γλουτένη	\N	0	rgba(71,95,81,1.0)	#FFFFFF	f	#475F51	1	Χωρίς Γλουτένη
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-06-01 21:45:57.827982+00	9	фывфывфыв	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430 [ru]", "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430 [en]"]}}]	10	1
2	2026-06-01 21:51:34.540896+00	1	Classic Central Asian Plov	2	[]	10	1
3	2026-06-01 21:51:49.85357+00	9	фывфывфыв	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043b\\u043d\\u043e\\u0435 \\u043e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435 [en]"]}}]	10	1
4	2026-06-01 21:52:28.973851+00	9	Baursak	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430 [ru]", "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430 [en]"]}}]	10	1
5	2026-06-01 21:57:49.686539+00	9	Baursak	2	[{"changed": {"fields": ["\\u041a\\u0440\\u0430\\u0442\\u043a\\u043e\\u0435 \\u043e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435 [ru]"]}}]	10	1
6	2026-06-01 22:54:19.728394+00	10	Baursak (Fried Dough)	3		10	1
7	2026-06-01 22:54:19.728471+00	9	Baursak	3		10	1
8	2026-06-01 22:54:19.728515+00	8	Kuurdak (Fried Meat and Onions)	3		10	1
9	2026-06-01 22:54:19.72854+00	7	Traditional Beshbarmak	3		10	1
10	2026-06-01 22:54:19.728564+00	6	Rich Shurpa Soup	3		10	1
11	2026-06-01 22:54:19.728587+00	5	Lamb Shashlik	3		10	1
12	2026-06-01 22:54:19.728608+00	4	Baked Samsa	3		10	1
13	2026-06-01 22:54:19.728641+00	3	Steamed Manti	3		10	1
14	2026-06-01 22:54:19.728679+00	2	Hand‑pulled Lagman	3		10	1
15	2026-06-01 22:54:19.728698+00	1	Classic Central Asian Plov	3		10	1
16	2026-06-01 23:13:25.711698+00	19	Baursak (Fried Dough)	3		10	1
17	2026-06-01 23:13:25.711802+00	18	Kuurdak (Fried Meat and Onions)	3		10	1
18	2026-06-01 23:13:25.711854+00	17	Traditional Beshbarmak	3		10	1
19	2026-06-01 23:13:25.711898+00	16	Rich Shurpa Soup	3		10	1
20	2026-06-01 23:13:25.711939+00	15	Lamb Shashlik	3		10	1
21	2026-06-01 23:13:25.711976+00	14	Baked Samsa	3		10	1
22	2026-06-01 23:13:25.712011+00	13	Steamed Manti	3		10	1
23	2026-06-01 23:13:25.712046+00	12	Hand‑pulled Lagman	3		10	1
24	2026-06-01 23:13:25.712081+00	11	Classic Central Asian Plov	3		10	1
25	2026-06-01 23:28:24.008182+00	30	Шорпо	3		10	1
26	2026-06-01 23:28:24.008247+00	31	Мастава	3		10	1
27	2026-06-01 23:28:24.008285+00	32	Плов	3		10	1
28	2026-06-01 23:28:24.008315+00	33	Куурдак	3		10	1
29	2026-06-01 23:28:24.008342+00	38	Манты	3		10	1
30	2026-06-01 23:28:24.008368+00	34	Шашлык	3		10	1
31	2026-06-01 23:28:24.008404+00	39	Кебаб	3		10	1
32	2026-06-01 23:28:24.008429+00	35	Лагман	3		10	1
33	2026-06-01 23:28:24.008453+00	36	Ганфан	3		10	1
34	2026-06-01 23:28:24.008478+00	37	Долма	3		10	1
35	2026-06-01 23:28:30.970163+00	24	Супы	3		7	1
36	2026-06-01 23:28:30.970247+00	25	Горячие блюда	3		7	1
37	2026-06-01 23:28:30.970302+00	26	Гриль	3		7	1
38	2026-06-01 23:28:30.970361+00	27	Лапша	3		7	1
39	2026-06-01 23:28:30.970409+00	28	Рисовые блюда	3		7	1
40	2026-06-02 10:57:56.79421+00	29	Супы	2	[{"changed": {"fields": ["\\u0418\\u043a\\u043e\\u043d\\u043a\\u0430 (SVG)"]}}]	7	1
41	2026-06-02 11:13:22.184527+00	34	Черти	1	[{"added": {}}]	7	1
42	2026-06-02 12:55:35.245257+00	40	Шорпо	2	[{"changed": {"fields": ["\\u0413\\u043b\\u0430\\u0432\\u043d\\u043e\\u0435 \\u0444\\u043e\\u0442\\u043e"]}}]	10	1
43	2026-06-02 12:56:02.310192+00	40	Шорпо	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e 2 (\\u043d\\u0435\\u043e\\u0431\\u044f\\u0437\\u0430\\u0442\\u0435\\u043b\\u044c\\u043d\\u043e)", "\\u0424\\u043e\\u0442\\u043e 3 (\\u043d\\u0435\\u043e\\u0431\\u044f\\u0437\\u0430\\u0442\\u0435\\u043b\\u044c\\u043d\\u043e)"]}}]	10	1
44	2026-06-02 13:18:08.791086+00	41	Мастава	2	[{"changed": {"fields": ["\\u0413\\u043b\\u0430\\u0432\\u043d\\u043e\\u0435 \\u0444\\u043e\\u0442\\u043e"]}}]	10	1
45	2026-06-02 13:34:18.978769+00	40	232131asdada	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430 [en]", "\\u041a\\u0440\\u0430\\u0442\\u043a\\u043e\\u0435 \\u043e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435 [en]", "\\u041f\\u043e\\u043b\\u043d\\u043e\\u0435 \\u043e\\u043f\\u0438\\u0441\\u0430\\u043d\\u0438\\u0435 [en]"]}}]	10	1
46	2026-06-02 16:06:54.939327+00	1	Острое	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u044b\\u0432\\u0430\\u0442\\u044c \\u043d\\u0430 \\u043a\\u0430\\u0440\\u0442\\u043e\\u0447\\u043a\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430"]}}]	11	1
47	2026-06-02 16:06:54.942124+00	2	Новинка	2	[{"changed": {"fields": ["\\u041f\\u043e\\u043a\\u0430\\u0437\\u044b\\u0432\\u0430\\u0442\\u044c \\u043d\\u0430 \\u043a\\u0430\\u0440\\u0442\\u043e\\u0447\\u043a\\u0435 \\u0431\\u043b\\u044e\\u0434\\u0430"]}}]	11	1
48	2026-06-02 16:21:03.281425+00	40	232131asdada	2	[{"changed": {"fields": ["\\u0422\\u0435\\u0433\\u0438"]}}]	10	1
49	2026-06-02 16:21:28.775845+00	40	232131asdada	2	[]	10	1
50	2026-06-02 16:24:38.791243+00	1	Острое	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [en]", "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [ky]", "\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)", "\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)"]}}]	11	1
51	2026-06-02 16:24:43.276733+00	2	Новинка	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [en]", "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [ky]", "\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)", "\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)"]}}]	11	1
52	2026-06-02 16:31:36.658951+00	40	232131asdada	2	[]	10	1
53	2026-06-02 16:53:39.831975+00	2	Новинка	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)", "\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)"]}}]	11	1
54	2026-06-02 16:56:25.624668+00	2	Новинка	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)", "\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (RGBA)"]}}]	11	1
55	2026-06-02 16:59:40.655247+00	2	Новинка	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (RGBA)"]}}]	11	1
56	2026-06-02 17:18:45.031826+00	2	Новинка	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [ru]"]}}]	11	1
57	2026-06-02 17:18:59.207061+00	2	NEW	2	[{"changed": {"fields": ["\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [en]", "\\u041d\\u0430\\u0437\\u0432\\u0430\\u043d\\u0438\\u0435 [ky]"]}}]	11	1
58	2026-06-02 17:19:30.336212+00	2	NEW	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)"]}}]	11	1
59	2026-06-02 17:19:50.27538+00	2	NEW	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0444\\u043e\\u043d\\u0430 (HEX)"]}}]	11	1
60	2026-06-02 17:40:33.78604+00	2	NEW	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)"]}}]	11	1
61	2026-06-02 17:40:59.992821+00	2	NEW	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)", "\\u041f\\u0440\\u043e\\u0437\\u0440\\u0430\\u0447\\u043d\\u043e\\u0441\\u0442\\u044c \\u0444\\u043e\\u043d\\u0430 (0\\u20131)"]}}]	11	1
62	2026-06-02 17:41:35.860042+00	2	NEW	2	[{"changed": {"fields": ["\\u0426\\u0432\\u0435\\u0442 \\u0442\\u0435\\u043a\\u0441\\u0442\\u0430 (HEX)", "\\u041f\\u0440\\u043e\\u0437\\u0440\\u0430\\u0447\\u043d\\u043e\\u0441\\u0442\\u044c \\u0444\\u043e\\u043d\\u0430 (0\\u20131)"]}}]	11	1
63	2026-06-02 18:20:48.994686+00	42	Плов	2	[{"changed": {"fields": ["\\u0413\\u043b\\u0430\\u0432\\u043d\\u043e\\u0435 \\u0444\\u043e\\u0442\\u043e"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	category
8	core	combo
9	core	combocategory
10	core	dish
11	core	tag
12	orders	order
13	orders	orderitem
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-01 21:38:30.170077+00
2	auth	0001_initial	2026-06-01 21:38:30.218824+00
3	admin	0001_initial	2026-06-01 21:38:30.242016+00
4	admin	0002_logentry_remove_auto_add	2026-06-01 21:38:30.253074+00
5	admin	0003_logentry_add_action_flag_choices	2026-06-01 21:38:30.263026+00
6	contenttypes	0002_remove_content_type_name	2026-06-01 21:38:30.286787+00
7	auth	0002_alter_permission_name_max_length	2026-06-01 21:38:30.297439+00
8	auth	0003_alter_user_email_max_length	2026-06-01 21:38:30.30856+00
9	auth	0004_alter_user_username_opts	2026-06-01 21:38:30.318868+00
10	auth	0005_alter_user_last_login_null	2026-06-01 21:38:30.331914+00
11	auth	0006_require_contenttypes_0002	2026-06-01 21:38:30.334722+00
12	auth	0007_alter_validators_add_error_messages	2026-06-01 21:38:30.346776+00
13	auth	0008_alter_user_username_max_length	2026-06-01 21:38:30.360341+00
14	auth	0009_alter_user_last_name_max_length	2026-06-01 21:38:30.370346+00
15	auth	0010_alter_group_name_max_length	2026-06-01 21:38:30.382739+00
16	auth	0011_update_proxy_permissions	2026-06-01 21:38:30.400758+00
17	auth	0012_alter_user_first_name_max_length	2026-06-01 21:38:30.41333+00
18	core	0001_initial	2026-06-01 21:38:30.429744+00
19	core	0002_dish_short_description_dish_short_description_en_and_more	2026-06-01 21:38:30.459372+00
20	core	0003_category_icon_dish_image_2_dish_image_3_and_more	2026-06-01 21:38:30.476431+00
21	core	0004_combocategory_combo	2026-06-01 21:38:30.499937+00
22	sessions	0001_initial	2026-06-01 21:38:30.510819+00
23	core	0005_rename_description_kg_category_description_ky_and_more	2026-06-01 22:44:14.246334+00
24	core	0006_tag_dish_tags	2026-06-02 13:59:46.457896+00
25	core	0007_tag_color_bg_tag_color_text_tag_show_on_card	2026-06-02 14:24:48.663933+00
26	core	0008_alter_tag_options_tag_title_ru_alter_tag_title_en_and_more	2026-06-02 15:46:22.243631+00
27	core	0009_tag_color_bg_hex_alter_tag_color_bg	2026-06-02 15:52:49.9134+00
28	core	0010_alter_tag_color_bg	2026-06-02 16:58:42.855126+00
29	core	0011_tag_opacity	2026-06-02 17:27:20.186938+00
30	orders	0001_initial	2026-07-04 22:59:46.919716+00
31	core	0012_dish_weight_alter_dish_image	2026-07-06 07:45:47.896345+00
32	core	0013_remove_category_description_ky_and_more	2026-08-12 09:36:18.785846+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
iv16qvg05msh0r9leprnnrb2ahnrceik	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wUAOV:0HXdD4u1o7IvRQJc5w7sa6RaMSAFmAqVBTxHyuG9U0w	2026-06-15 21:41:59.12461+00
5bt2fst1clbzzpzzcx5ps6ndysrzd1w5	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wUAS8:WujZierUt1Gn0UuAvMUlwlu8T5p9sQMh5VXro5w5lDA	2026-06-15 21:45:44.231651+00
833wnuu5elnibdve9d175awufgims64d	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wfiou:qu80ZoYsGZ4wPUYm1XoyAfFHljZiRT4I9ZbPQXPea0w	2026-07-17 18:41:00.981231+00
pdb1b0g291ecyb8e6gvu2atcdpwtw6o8	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wghKS:pF8BnEBBKhmUWkuj0uImxgl-rv9B_BtaAMMaW7T-rPY	2026-07-20 11:17:36.895646+00
tvy9hknup61ngi6jhc2l6zyhdgtwpr64	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wmVTF:Fzs4lTj1V7GzwdIe31JROx0EwbW6i0ZHrZdpCmUzte8	2026-08-05 11:50:41.527924+00
f4bbgucf22p17hfpegutcv47txcq2azt	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wmnmo:Zd13p4OUUPkvqwY2rd9t3HG0f-3iTZ8jkvASbXguSGw	2026-08-06 07:24:06.612889+00
633kes3k33tzgtqj0lg29g266uje48ae	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wmo4z:CeqabILBvFisnA8ek9MmXEVSEpwcVXoQE52_1XPbn3U	2026-08-06 07:42:53.011402+00
dhbp8ginbmp9gms9daciaxxocvk9imd0	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wmoL1:AcMNWN8ODncREtvobZq7AA1hlxMDDQ5o_oDzlZJSOiQ	2026-08-06 07:59:27.313082+00
6v4ynmy84sjwe6a2zuvcpfzd1yii2q7e	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wmsow:kaytcl-Ew9xQSIEBAkg1wKRhPd_4CGZWP1CRZnyFock	2026-08-06 12:46:38.885125+00
ar19ipv20zgv5vuohnh1xgfjl80dr0ps	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wmspJ:souSnhnJxJG7Shp3Ya88S9Hll2NAFMQAgi8MWKR6AF8	2026-08-06 12:47:01.770619+00
lq8zx8dmuh5baunx9ptlaolc6t61phyy	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wmsrT:AU9X1dnGU5ggRomgu_mz1EO3RtlWe0nnan23ZpndPm8	2026-08-06 12:49:15.717583+00
jjxry955vwig2yk8jp5r5vkafqohxt7e	.eJxVjEEOwiAQRe_C2pBSKDgu3XsGMsMMUjUlKe3KeHfbpAvd_vfef6uI61Li2mSOI6uLMur0uxGmp0w74AdO96pTnZZ5JL0r-qBN3yrL63q4fwcFW9lqx5aQTMgifepM7gQAnHgemCU4gB5SIhS_cToLuBw8YR7E9E6cterzBRQIOQY:1wmsre:UAoUFzgP_XVp_uQmT4CVgEf9Nf9KwKLtCSjJDVeejI0	2026-08-06 12:49:26.328473+00
iw6fq5kyrqecj1iv11v364wdlk8t9qfb	.eJxVjEEOwiAQRe_C2pDCOFBcuu8ZCAyDVA0kpV0Z765NutDtf-_9l_BhW4vfOi9-TuIitDj9bjHQg-sO0j3UW5PU6rrMUe6KPGiXU0v8vB7u30EJvXzrMzujLJiIRjt0jDZag5CcATIuB0CreQTOg4LAioeRCDEROYg5sRXvD78ON8Y:1wmxHM:xh9AyWDWeW76jBDcB4cSjUsyHl9G0Cbh-N-LAw_f4AA	2026-08-06 17:32:16.932952+00
\.


--
-- Data for Name: orders_order; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders_order (id, customer_name, customer_phone, address, comment, total_amount, status, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: orders_orderitem; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.orders_orderitem (id, dish_name, price, quantity, dish_id, order_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_category_id_seq', 164, true);


--
-- Name: core_combo_dishes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_combo_dishes_id_seq', 1, false);


--
-- Name: core_combo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_combo_id_seq', 9, true);


--
-- Name: core_combocategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_combocategory_id_seq', 3, true);


--
-- Name: core_dish_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_dish_id_seq', 1268, true);


--
-- Name: core_dish_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_dish_tags_id_seq', 100, true);


--
-- Name: core_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.core_tag_id_seq', 35, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 63, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_order_id_seq', 1, false);


--
-- Name: orders_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.orders_orderitem_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_category core_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_category
    ADD CONSTRAINT core_category_pkey PRIMARY KEY (id);


--
-- Name: core_combo_dishes core_combo_dishes_combo_id_dish_id_6102d2ab_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo_dishes
    ADD CONSTRAINT core_combo_dishes_combo_id_dish_id_6102d2ab_uniq UNIQUE (combo_id, dish_id);


--
-- Name: core_combo_dishes core_combo_dishes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo_dishes
    ADD CONSTRAINT core_combo_dishes_pkey PRIMARY KEY (id);


--
-- Name: core_combo core_combo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo
    ADD CONSTRAINT core_combo_pkey PRIMARY KEY (id);


--
-- Name: core_combocategory core_combocategory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combocategory
    ADD CONSTRAINT core_combocategory_pkey PRIMARY KEY (id);


--
-- Name: core_dish core_dish_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish
    ADD CONSTRAINT core_dish_pkey PRIMARY KEY (id);


--
-- Name: core_dish_tags core_dish_tags_dish_id_tag_id_bebbc3c5_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish_tags
    ADD CONSTRAINT core_dish_tags_dish_id_tag_id_bebbc3c5_uniq UNIQUE (dish_id, tag_id);


--
-- Name: core_dish_tags core_dish_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish_tags
    ADD CONSTRAINT core_dish_tags_pkey PRIMARY KEY (id);


--
-- Name: core_tag core_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_tag
    ADD CONSTRAINT core_tag_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: orders_order orders_order_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders_order
    ADD CONSTRAINT orders_order_pkey PRIMARY KEY (id);


--
-- Name: orders_orderitem orders_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_combo_category_id_528edf04; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_combo_category_id_528edf04 ON public.core_combo USING btree (category_id);


--
-- Name: core_combo_dishes_combo_id_fa87a646; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_combo_dishes_combo_id_fa87a646 ON public.core_combo_dishes USING btree (combo_id);


--
-- Name: core_combo_dishes_dish_id_32bef464; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_combo_dishes_dish_id_32bef464 ON public.core_combo_dishes USING btree (dish_id);


--
-- Name: core_dish_category_id_229e3e0d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_dish_category_id_229e3e0d ON public.core_dish USING btree (category_id);


--
-- Name: core_dish_tags_dish_id_9452be86; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_dish_tags_dish_id_9452be86 ON public.core_dish_tags USING btree (dish_id);


--
-- Name: core_dish_tags_tag_id_3c02adfa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_dish_tags_tag_id_3c02adfa ON public.core_dish_tags USING btree (tag_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: orders_orderitem_dish_id_a7496bf4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX orders_orderitem_dish_id_a7496bf4 ON public.orders_orderitem USING btree (dish_id);


--
-- Name: orders_orderitem_order_id_fe61a34d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX orders_orderitem_order_id_fe61a34d ON public.orders_orderitem USING btree (order_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_combo core_combo_category_id_528edf04_fk_core_combocategory_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo
    ADD CONSTRAINT core_combo_category_id_528edf04_fk_core_combocategory_id FOREIGN KEY (category_id) REFERENCES public.core_combocategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_combo_dishes core_combo_dishes_combo_id_fa87a646_fk_core_combo_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo_dishes
    ADD CONSTRAINT core_combo_dishes_combo_id_fa87a646_fk_core_combo_id FOREIGN KEY (combo_id) REFERENCES public.core_combo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_combo_dishes core_combo_dishes_dish_id_32bef464_fk_core_dish_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_combo_dishes
    ADD CONSTRAINT core_combo_dishes_dish_id_32bef464_fk_core_dish_id FOREIGN KEY (dish_id) REFERENCES public.core_dish(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dish core_dish_category_id_229e3e0d_fk_core_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish
    ADD CONSTRAINT core_dish_category_id_229e3e0d_fk_core_category_id FOREIGN KEY (category_id) REFERENCES public.core_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dish_tags core_dish_tags_dish_id_9452be86_fk_core_dish_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish_tags
    ADD CONSTRAINT core_dish_tags_dish_id_9452be86_fk_core_dish_id FOREIGN KEY (dish_id) REFERENCES public.core_dish(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dish_tags core_dish_tags_tag_id_3c02adfa_fk_core_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_dish_tags
    ADD CONSTRAINT core_dish_tags_tag_id_3c02adfa_fk_core_tag_id FOREIGN KEY (tag_id) REFERENCES public.core_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_dish_id_a7496bf4_fk_core_dish_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_dish_id_a7496bf4_fk_core_dish_id FOREIGN KEY (dish_id) REFERENCES public.core_dish(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders_orderitem orders_orderitem_order_id_fe61a34d_fk_orders_order_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders_orderitem
    ADD CONSTRAINT orders_orderitem_order_id_fe61a34d_fk_orders_order_id FOREIGN KEY (order_id) REFERENCES public.orders_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 1bdYbQXAI7hOfpHnkCJMsugxleSTlCAKc9dEQNSeguYIXBKhvd9Lwl969IpBdKy

