# Generated by Django 6.0.5 on 2026-05-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_kg', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название блюда')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название блюда')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание блюда')),
                ('description_en', models.TextField(null=True, verbose_name='Описание блюда')),
                ('description_kg', models.TextField(null=True, verbose_name='Описание блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (KGS)')),
                ('image', models.ImageField(upload_to='dishes/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['category', 'order'],
            },
        ),
    ]
