# Generated by Django 6.0.5 on 2026-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='short_description',
            field=models.CharField(default='', help_text='Отображается в общем списке меню (до 255 символов)', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='short_description_en',
            field=models.CharField(help_text='Отображается в общем списке меню (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='dish',
            name='short_description_kg',
            field=models.CharField(help_text='Отображается в общем списке меню (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='dish',
            name='short_description_ru',
            field=models.CharField(help_text='Отображается в общем списке меню (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(help_text='Отображается на отдельной странице блюда', verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_en',
            field=models.TextField(help_text='Отображается на отдельной странице блюда', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_kg',
            field=models.TextField(help_text='Отображается на отдельной странице блюда', null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_ru',
            field=models.TextField(help_text='Отображается на отдельной странице блюда', null=True, verbose_name='Полное описание'),
        ),
    ]
