# Generated by Django 6.0.5 on 2026-05-29 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_short_description_dish_short_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, help_text='Загрузите иконку категории в формате .svg', null=True, upload_to='categories/icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка (SVG)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото 2 (необязательно)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото 3 (необязательно)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dishes/', verbose_name='Главное фото'),
        ),
    ]
