# Generated by Django 6.0.5 on 2026-05-31 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_icon_dish_image_2_dish_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории сборки')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название категории сборки')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название категории сборки')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Название категории сборки')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('description_kg', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('icon', models.FileField(blank=True, help_text='Загрузите иконку категории сборок в формате .svg', null=True, upload_to='combo_categories/icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Иконка (SVG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Категория сборки',
                'verbose_name_plural': 'Категории сборок',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сборки')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название сборки')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название сборки')),
                ('title_kg', models.CharField(max_length=255, null=True, verbose_name='Название сборки')),
                ('short_description', models.CharField(help_text='Отображается в общем списке сборок (до 255 символов)', max_length=255, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(help_text='Отображается в общем списке сборок (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(help_text='Отображается в общем списке сборок (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание')),
                ('short_description_kg', models.CharField(help_text='Отображается в общем списке сборок (до 255 символов)', max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(help_text='Отображается на отдельной странице сборки', verbose_name='Полное описание')),
                ('description_ru', models.TextField(help_text='Отображается на отдельной странице сборки', null=True, verbose_name='Полное описание')),
                ('description_en', models.TextField(help_text='Отображается на отдельной странице сборки', null=True, verbose_name='Полное описание')),
                ('description_kg', models.TextField(help_text='Отображается на отдельной странице сборки', null=True, verbose_name='Полное описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена сборки (KGS)')),
                ('image', models.ImageField(upload_to='combos/', verbose_name='Главное фото')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Фото 2 (необязательно)')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='combos/', verbose_name='Фото 3 (необязательно)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('dishes', models.ManyToManyField(related_name='combos', to='core.dish', verbose_name='Блюда в сборке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='core.combocategory', verbose_name='Категория сборки')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['category', 'order'],
            },
        ),
    ]
