# Generated by Django 6.0.5 on 2026-06-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_combocategory_combo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='short_description_kg',
            new_name='short_description_ky',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='combocategory',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='combocategory',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='short_description_kg',
            new_name='short_description_ky',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
