# Generated by Django 6.0.5 on 2026-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_description_kg_category_description_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (KY)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='core.tag', verbose_name='Теги'),
        ),
    ]
