# Generated by Django 6.0.5 on 2026-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_dish_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_bg',
            field=models.CharField(default='rgba(0,0,0,0.1)', max_length=20, verbose_name='Цвет фона (CSS)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color_text',
            field=models.CharField(default='#2B1E17', max_length=20, verbose_name='Цвет текста (HEX)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='show_on_card',
            field=models.BooleanField(default=False, verbose_name='Показывать на карточке блюда'),
        ),
    ]
