# Generated by Django 6.0.5 on 2026-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tag_options_tag_title_ru_alter_tag_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_bg_hex',
            field=models.CharField(default='#B8860B', max_length=20, verbose_name='Цвет фона (HEX)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color_bg',
            field=models.CharField(default='rgba(184,134,11,0.15)', max_length=50, verbose_name='Цвет фона (RGBA)'),
        ),
    ]
