# Generated by Django 6.0.5 on 2026-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag_color_bg_hex_alter_tag_color_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color_bg',
            field=models.CharField(default='rgba(184,134,11,1)', max_length=50, verbose_name='Цвет фона (RGBA)'),
        ),
    ]
