# Generated by Django 6.0.5 on 2026-06-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tag_color_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='opacity',
            field=models.FloatField(default=1.0, verbose_name='Прозрачность фона (0–1)'),
        ),
    ]
