# Generated by Django 6.0.5 on 2026-07-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tag_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес/Объем'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Главное фото'),
        ),
    ]
